/**
 * @file test_foundation_status.c
 * @brief 验证基础状态码的稳定数值契约。
 */
#include "test_support.h"
#include "foundation_status.h"

/**
 * @brief 验证所有基础状态码保持连续且稳定。
 * @return 测试通过时返回 0，否则返回 1。
 */
int main(void)
{
    TEST_ASSERT(FOUNDATION_STATUS_OK == 0);
    TEST_ASSERT(FOUNDATION_STATUS_INVALID_ARGUMENT == 1);
    TEST_ASSERT(FOUNDATION_STATUS_NOT_INITIALIZED == 2);
    TEST_ASSERT(FOUNDATION_STATUS_INVALID_STATE == 3);
    TEST_ASSERT(FOUNDATION_STATUS_OUT_OF_RANGE == 4);
    TEST_ASSERT(FOUNDATION_STATUS_EMPTY == 5);
    TEST_ASSERT(FOUNDATION_STATUS_FULL == 6);
    TEST_ASSERT(FOUNDATION_STATUS_BUFFER_TOO_SMALL == 7);
    TEST_ASSERT(FOUNDATION_STATUS_INVALID_DATA == 8);
    TEST_ASSERT(FOUNDATION_STATUS_OVERFLOW == 9);
    TEST_ASSERT(FOUNDATION_STATUS_BUSY == 10);
    TEST_ASSERT(FOUNDATION_STATUS_TIMEOUT == 11);
    TEST_ASSERT(FOUNDATION_STATUS_IO_ERROR == 12);
    TEST_ASSERT(FOUNDATION_STATUS_UNAVAILABLE == 13);
    TEST_ASSERT(FOUNDATION_STATUS_NOT_FOUND == 14);
    TEST_ASSERT(FOUNDATION_STATUS_CANCELLED == 15);
    TEST_ASSERT(FOUNDATION_STATUS_INTERNAL_ERROR == 16);
    TEST_ASSERT(FOUNDATION_STATUS_INVALID_CONTEXT == 17);
    TEST_ASSERT(FOUNDATION_STATUS_UNSUPPORTED == 18);
    return 0;
}
